theme: minima

sass:
  style: compressed

plugins:
  - jekyll-seo-tag

# Puedes añadir un título y descripción para que aparezcan en la cabecera
title: Curs d'implementació de sistemes operatius
description: Material del curs de Machine Learning desenvolupat per Mireia Consarnau.
